APPLICATION=shell

BOARD ?= native

RIOTBASE ?= $(CURDIR)/..

FEATURES_REQUIRED = periph_i2c

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += xtimer
USEMODULE += printf_float

USEPKG += minmea

include $(RIOTBASE)/Makefile.include